### ISSUE TITLE
Problem at words section

### ISSUE THREAD

**Issue by iamshouvikmitra** [naseemali925/Lumos#1]
Words like Voluntary and Volunteer have same images

Words like vote appear twice

**Comment by inaseem** [comment]
Words Like Voluntary And Volunteer Have Same Signs Because They Are Used Indifferently Of Each Other In Sign Language. No Words Appear Twice Now. Thanks For Pointing That Out.

**Comment by iamshouvikmitra** [comment]
[Image]

Check out vote


Shouvik Mitra.

________________________________

**Comment by inaseem** [comment]
Check Out The Latest Commit Of Lumos
